Mars rover initial working solution
nilenso/raghavs-onboarding pull request #2
Opened 2023-03-28 10:34 UTC by raghavyuva

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (println rover-cur-pos)
debug statement, remove

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +                                 rover-current-instruction]
Remove notions of "current" from this function. Strive to create functions that are independent of others, and can be reused in other contexts as well.

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (if (= rover-current-instruction (first "L"))
Use character notations: `\L`

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +      (move-rover rover-cur-pos))))
- What if the instruction is something other than L or R or M?
- Is an if-else ladder the best way to implement this? What are the other options, and what would you pick? => Leverage clojure.core.
- DO NOT FAIL SILENTLY
- Apply learnings from 4clojure

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +                                      "E" "N")
- Use a literal hash map
- Destructure the position into what you want.

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +                        heading-direction]
I'd put these args into the same line.

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (println (rovers-information  ['(5 5) '(1 2 "N") "LMLMLMLMM"])))
Do not use literal lists for collections. Use vectors.

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (concat (vec (drop-last rover-cur-pos)) [heading-direction]))
Reconsider this function after using destructuring well over the rest of the code.

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +                                      "W" (move-horizontal rover-cur-pos dec))]
- These are not functions, they are evaluated into values
- All the functions are evaluated, even if you only want to evaluate one function for the given direction

2023-03-29 06:28 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +              (func (second rover-cur-pos)))
This is not readable. <feedback offline>

2023-03-30 07:30 UTC, shhivam commented
@raghavyuva Srihari has already done a comprehensive review.
Would just like to mention about your git hygiene. 

For a problem like mars-rover, you could have broken down the commits in an atomic way. 

For example, in this [ec0a4b25e459035ba33a0c6edd86d6507fde41c8](https://github.com/nilenso/raghavs-onboarding/pull/2/commits/ec0a4b25e459035ba33a0c6edd86d6507fde41c8), you have lumped all the solution in one commit (btw, which also contains unrelated changes from README, LICENSE, etc).

Many a times, developers review PRs commit-by-commit for large PRs and there are a lot of other reasons where git hygiene is important.

I have linked some resources for Shahn [here](https://nilenso.slack.com/archives/C04UWUT4HA4/p1680155390190629); will recommend that you read through those articles and implement it.

2023-03-30 09:56 UTC, raghavyuva commented on mars_rover/.gitignore
> +.hg/
Lein new app does add these mercurial files by default, i tried creating a dummy project to verify the same. (Mercurial files are also used for version controlling alternative to git)

2023-03-30 09:56 UTC, raghavyuva commented on mars_rover/CHANGELOG.md
> +[0.1.1]: https://sourcehost.site/your-name/mars_rover/compare/0.1.0...0.1.1
Cleaned the file

2023-03-30 09:57 UTC, raghavyuva commented on mars_rover/doc/intro.md
> +TODO: write [great documentation](http://jacobian.org/writing/what-to-write/)
Cleaned the file

2023-03-30 09:57 UTC, raghavyuva commented on mars_rover/project.clj
> +  :url "http://example.com/FIXME"
Added description and url of the project here

2023-03-30 09:58 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (:gen-class))
gen-class is used to create java byte codes, and it also creates java class from the name provided to it.

2023-03-30 09:59 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (println (rovers-information  ['(5 5) '(1 2 "N") "LMLMLMLMM"])))
Used vectors and added line at the end of the file

2023-03-30 09:59 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (println (rovers-information  ['(5 5) '(1 2 "N") "LMLMLMLMM"])))
Changed the function name to `get-final-position`

2023-03-30 10:00 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +(defn rovers-information [rovers-list]
Used destructuring, changed the function name to `get-final-position`

2023-03-30 10:02 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (println rover-cur-pos)
Removed the debug statement from here

2023-03-30 10:02 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +                                 rover-current-instruction]
Removed notion of current throughout the file

2023-03-30 10:03 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +              (func (second rover-cur-pos)))
Refactored this

2023-03-30 10:03 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +                                      "W" (move-horizontal rover-cur-pos dec))]
Changed the behaviour of the code here

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +          instructions))
"Update" is still referring to a previous state, that you're updating. This function is stateless. This function has its own purpose. Try renaming this function to what it does, independently from how it's being used.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +;; updates the rover position by reducing instructions
Clojure has docstrings as a language construct, especially when defining functions. Use that instead of comments. And again here, try to stay away from using implementation details unless necessary.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (cond
When should we use `case`, and when is `cond` a better choice?

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +    :else
Formatting `cond` with the condition and expression on the same line makes it more readable. At the very least, add a newline between conditions.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +    (update-direction rover heading-direction)))
See how rotate right and rotate left are almost the same functions? What's the essence between the two? Try writing that down, and then see if that's a better solution than what you have right now.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (assoc rover 2 heading-direction))
It's not idiomatic to use `assoc` on a vector. Instead, consider returning the literal rover back. Or, consider using a data structure where using `assoc` would be idiomatic.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +      :else
Same note on formatting cond as below.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +  (let [[x-cord _ _] rover
This destructuring can happen in the function definition itself.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +    (assoc rover 0 updated-x-cord)))
If you want to update a specific element, there's another function for it.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +    (assoc rover 1 updated-y-cord)))
See how these two functions (horizontal and vertical) are very similar? Extract a common function, and then decide which one you want to use.

2023-03-31 06:13 UTC, ssrihari commented on mars_rover/src/mars_rover/core.clj
> +    (assoc rover 1 updated-y-cord)))
Or if you even want to use either of them. What's an alternative to writing these one-line functions?

2023-03-31 07:07 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +    (update-direction rover heading-direction)))
Yeah! thinking in this fashion did helped to converge the two functions into one optimal function!

2023-03-31 07:10 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (assoc rover 2 heading-direction))
Yeah! have saw that assoc has O(N) time complexity on vectors and O(log32 n) on maps. so returning a liter rover back is a nice approach here!

2023-03-31 07:11 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (let [[x-cord _ _] rover
Ah, didn't knew this, would definitely take this advice going forward!

2023-03-31 07:13 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +          instructions))
Changed the function name to `execute-instructions` because it executes the instruction to update the rover position

2023-03-31 07:14 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +;; updates the rover position by reducing instructions
Yeah, have changed all the comments to docstring, will use docstrings from now on.. okay will try to avoid implementation details too

2023-03-31 07:23 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (cond
Cond is kind a alternative to if-else-ladder where it evaluates expressions one by one until return value is boolean true.
Case is used in the same way as switch cases.

cond can be used when there are different conditions other than equality test.
case can be used when testing equality of the conditions.

2023-03-31 07:25 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +    :else
formatting cond with the conditions and expression on the same line looks prettier than adding a newline between, IMO, have done the changes.

2023-03-31 09:44 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +    (assoc rover 1 updated-y-cord)))
combined both vertical and horizontal function into one function.

2023-04-05 13:33 UTC, tfidfwastaken requested changes
Listen to the linter warning on this line, and change it accordingly.

2023-04-05 13:33 UTC, tfidfwastaken commented on mars_rover/test/mars_rover/core_test.clj
> +(ns mars-rover.core-test
What's good about your test suite:
* Assertions are clearly visible at the end of each test–this makes it easy to understand what your function does by looking at the test alone.
* The expected data is easy to inspect, as you have written the vector literal directly.

Good job :)

2023-04-05 13:33 UTC, tfidfwastaken commented on mars_rover/test/mars_rover/core_test.clj
> +    (is (= [4 3 "W"] (rotate [4 3 "S"] \R)))))
[suggestion] Look up table-driven tests, it might help you here and elsewhere in this file.

2023-04-10 08:07 UTC, qptr requested changes

2023-04-10 08:50 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (reduce (fn [acc item]
Yep, renamed it to `rover and instruction`

2023-04-10 08:51 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +    (throw (Exception. (str "instruction" " " instruction " " "is not valid")))))
Done

2023-04-10 08:56 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +(defn get-final-position
Agree. removed this function

2023-04-10 09:24 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +        updated-rover-y-cord (update rover 1 func)
Changed to `vertically-updated-rover` and `horizontally-updated-rover`

2023-04-10 10:03 UTC, raghavyuva commented on mars_rover/README.md
> +  lein run
No not mentioned, have made changes such that it takes cli arguments

2023-04-10 11:48 UTC, qptr reviewed
Left some minor comments. This is looking pretty good.

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +  [[x_cord y_cord _] bound-cord]
Can destructure more aggressively instead of using both destructuring and let bindings I think.

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +    (throw (Exception. (str "instruction" " " instruction " " "is not valid")))))
see: [format](https://clojuredocs.org/clojure.core/format)

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +(defn rover-out-of-bound
You can discuss this more with Atharva maybe, but if your function returns the exception instead of throwing it, you can use it in your tests.

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +  "Moves horizontal if direction is east or west. moves vertical if direction is north or south"
[nit] => ```Moves the rover by 1 step in the given direction```

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +               (if (is-in-bounds? moved-rover bound-cord)
I think bounds check belongs in the move function. You can think in terms of tests to help with this.

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +               (if (is-in-bounds? moved-rover bound-cord)
Be sure to test this as well.

2023-04-10 11:48 UTC, qptr commented on mars_rover/src/mars_rover/core.clj
> +(defn is-in-bounds?
[nit] boolean return value is assumed from the `?` in the function name. So it can just say `Returns whether rover is within the plateau`

2023-04-12 04:47 UTC, raghavyuva commented on mars_rover/test/mars_rover/core_test.clj
> +(deftest validate-get-position
Okay, will follow this pattern from now on.

2023-04-12 04:52 UTC, raghavyuva commented on mars_rover/src/mars_rover/core.clj
> +  (let [direction (last rover)]
the second one seems great! 
```
{:coordinates [5 6]
 :direction "N"}
```

2023-04-13 07:11 UTC, merged