Advent of code day2
nilenso/raghavs-onboarding pull request #5
Opened 2023-04-19 08:36 UTC by raghavyuva

### Thought Process

- Get the input and convert to vector of vector
- Get the outcome-score for the round
- Get the player-choice score for the round
- Sum over player-choice-score and outcome-score
- Return the total-score of the player

2023-04-24 14:09 UTC, olttwa requested changes

2023-04-24 14:09 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +  (reduce (fn [priority-sum rucksack]
This will be neater. 2 pointers for reduce:
1. Try to use a named function instead of defining an anonymous function. Define a function if needed.
2. Whenever possible, exploit the default 3rd argument. In this case, `0` need not be defined as the aggregation argument as reduce will default to that.
```Clojure
(reduce + (map compute-priority-sum rucksacks))
```

2023-04-24 14:09 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +      (let [first-line  (set (rucksack 0))
It isn't clear why we are converting a rucksack into a set? The function name is just to split a rucksack.

2023-04-24 14:09 UTC, olttwa commented on advent-of-code/test/probelm3_test.clj
> +(deftest test-letter-priority
`test-letter-priority` isn't a comprehensive test. A table-driven test would be the right way to test letter-priority is correct.

2023-04-25 04:52 UTC, raghavyuva commented on advent-of-code/LICENSE
> +Eclipse Public License - v 2.0
That was added by leiningen project template, do i need to remove that?

2023-04-25 05:15 UTC, raghavyuva commented on advent-of-code/src/problem3.clj
> +      (let [first-line  (set (rucksack 0))
We are converting it to set, So that we can perform intersection and get the common letters in an easy fashion. if we keep it in other data structures then we need to perform these operations manually,

2023-04-26 07:01 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +      (let [first-line  (set (rucksack 0))
The `split-rucksack` is overloaded to do 3 things: 
1. split into 3 lines
2. split into 2 compartments
3. Create a set of the rucksack.

Can we create separate methods for all 3?

2023-04-26 07:22 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +        rucksack-priority-sum  (reduce + priority)]
Entire file isn't properly formatted. Add an action to Github CI for linting? That'll automate such checks.
For example, Goose has a lint job that prevents merging of PRs until successful: https://github.com/nilenso/goose/actions/runs/4780094145/jobs/8497598357

2023-04-26 07:26 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +        common-letters (apply find-common-letters compartments)]
Acc to problem-statement, there's just 1 common-letter, right? Shall we rename this to `common-letter` for clarity?

2023-04-26 07:34 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +      (let [first-line  (set (rucksack 0))
In fact, we can compute a set in the `find-common-letters` function itself, as `set/intersection` is the only function that needs a set.

2023-04-26 07:38 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +(defn run-problem3 []
Because we're trying to solve both parts using same function, there's unnecessary duplication & confusion:

1. Computation of lines-to-string-vector is happening twice
2. `split-rucksack` is overloaded

Can we put end-functions in a reusable manner, and solve both parts by calling different functions?
For example, `find-common-letters` can be reused as it accepts variadic sets, but there should be 2 `compute-priority-sum` for both parts as the logic of 3 lines vs 1 line doesn't belong there.

2023-04-26 07:46 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +  (let [rucksacks (lines-to-string-vector data-file)]
Following returns the same result. Am I missing something?
```suggestion
  (let [rucksacks (str/split-lines data-file)]
```

2023-04-26 07:47 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +  (let [rucksack-vector-of-strings (lines-to-string-vector data-file)]
Following returns the same result. Am I missing something?
```suggestion
  (let [rucksacks (str/split-lines data-file)]
```

2023-04-26 07:47 UTC, olttwa commented on advent-of-code/src/problem3.clj
> +(defn lines-to-string-vector
This and `lines-to-string` can be deleted.

2023-04-26 07:54 UTC, olttwa commented on advent-of-code/LICENSE
> +Eclipse Public License - v 2.0
No need to remove, going ahead, have an understanding of License before adding one. 
https://choosealicense.com/

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

2023-04-26 10:12 UTC, tfidfwastaken commented on advent-of-code/project.clj
> +(defproject advent-of-code "0.1.0-SNAPSHOT"
@olttwa Raghav's 4clojure solutions used deps. We chose lein for this and mars-rover because:
* Exposure to a new dependency management tool, that's still heavily used in Clojure codebases
* Ease of getting started, the starter template comes with its own project template–this lets us focus on the current priority of craft structuring within a single namespace.

We will make a more deliberate decision for future projects, where managing package structure and external dependency becomes important.

2023-05-11 07:26 UTC, tfidfwastaken approved these changes

2023-05-11 07:28 UTC, merged